### ISSUE TITLE
n icon for ticket names

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#101]
If these phrases are used, the ```n``` should be replaced with an accessible ```general-n-ticket``` icon:

- nnetwork
- nticket
- ntrain
- nbus
- nNetwork
- nTicket
- nTrain
- nBus

Screen readers should read it as ```n-network```, not ```nn-etwork```

**Comment by mrmjprice** [comment]
This was previously done with javascript.

It should be the same wherever it is used, regardless of it being in paragraph or header.

**Comment by daylesalmon** [comment]
This should be resolved via: https://github.com/wmcadigital/wmn-design-system/pull/782

**Comment by daylesalmon** [comment]
New update: https://github.com/wmcadigital/wmn-design-system/pull/800
The logic will be in the next release of Umbraco too!
