### ISSUE TITLE
Change "Plan your journey" content to a grid with sidebar

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#104]
Currently, it's a custom DocType which is a redirect to the live site. We need it to be a content page.

**Comment by catiarodriguescosta** [comment]
- [ ] Permissions updated

Then, when we next go live we will:
- [ ] Rename the plan your journey page to "plan your journey - old"
- [ ] 	Create a new sidebar grid page and call it "plan your journey"
- [ ] 	Move all child nodes from old page to the new one
- [ ] 	Delete the old parent node "plan your journey - old"
- [ ] 	Content restore to dev/local, so everything is in sync
