### ISSUE TITLE
Headings not showing correct on 'Cycle hub' T&Cs page

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#116]
## What's wrong?

H2 headings are not rendering correctly on 'Cycle hub' T&Cs page. The font-weight and colour is incorrect

As a result of the headings not showing, the navigation card is blank.

https://beta.wmnetwork.co.uk/what-we-do/terms-and-conditions/cycle-hub/

**Comment by mrmjprice** [comment]
Fixed - if this happens on other pages, you need to select each header, go to format styles and make sure Header 2 isn't selected.

<img width="591" alt="Screenshot 2021-05-14 at 13 30 49" src="https://user-images.githubusercontent.com/10854265/118270963-9adba480-b4b8-11eb-92cc-5fe1826dbc66.png">
