### ISSUE TITLE
No side bar content on 'Cycle locker' T&Cs page and numbered list not formatted correctly 

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#117]
## What's wrong?
* Numbered lists are in the standard body text colour
* The layout has been set up to have a left sidebar, even though there is nothing there at the moment

https://beta.wmnetwork.co.uk/what-we-do/terms-and-conditions/cycle-locker/

**Comment by mrmjprice** [comment]
What do you think we should do with this page? Recreate it left aligned?

**Comment by mrmjprice** [comment]
Please can you create a separate issue about number formatting
