### ISSUE TITLE
Not enough spacing between heading and content card on 'Find a Swift collector or kiosk' page

### ISSUE THREAD

**Issue by somtmee** [wmcadigital/wmn-cms#120]
## What's wrong?
Swift kiosk is a h2. Feels like there should be more padding/margin between itself and the Find a Swift collector content card

<img width="526" alt="Screenshot 2021-05-14 at 13 19 07" src="https://user-images.githubusercontent.com/68843432/118269719-fa38b500-b4b6-11eb-9be6-7072817a7d12.png">

**Comment by mrmjprice** [comment]
Closing as linked to this https://github.com/wmcadigital/wmn-cms/issues/107
