### ISSUE TITLE
Add 3-column grid as a new row option

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-cms#121]
Please create 3 column grid so we can have 3 content cards in one row. Similar like Swift page here. 

<img width="348" alt="Screenshot 2021-05-07 at 12 02 38" src="https://user-images.githubusercontent.com/57525718/118270690-489a8380-b4b8-11eb-92f1-547d8cb34d0d.png">

This grid will be used for pages where we have many content cards, like this one https://beta.wmnetwork.co.uk/plan-your-journey/ways-to-travel/

**Comment by mrmjprice** [comment]
Expecting to see it as an option here:
<img width="516" alt="Screenshot 2021-05-14 at 13 32 43" src="https://user-images.githubusercontent.com/10854265/118271211-e2fac700-b4b8-11eb-9fc0-6e986c52cfc3.png">

**Comment by mrmjprice** [comment]
Added in the next Umbraco release
