### ISSUE TITLE
No side bar content on 'Concessionary pass' T&Cs page and numbered list not formatted correctly

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#122]
## What's wrong?
* Numbered lists are in the standard body text colour
* The layout has been set up to have a left sidebar, even though there is nothing there at the moment

https://beta.wmnetwork.co.uk/what-we-do/terms-and-conditions/concessionary-pass/

**Comment by mrmjprice** [comment]
Again, should this be a left-aligned page layout do you think?

**Comment by jkmnch** [comment]
I think so as there are no headings so a navigation card isn't necessary on these pages
