### ISSUE TITLE
Contact an operator card on Get Help hub page links to the old Journey Planner

### ISSUE THREAD

**Issue by somtmee** [wmcadigital/wmn-cms#125]
## What's wrong?

The 'Contact an operator' content card on the [Get Help](https://beta.wmnetwork.co.uk/umbraco/#/content/content/edit/1333) page links to the operators page on the old website.

<img width="1033" alt="Screenshot 2021-05-14 at 13 52 49" src="https://user-images.githubusercontent.com/68843432/118273290-ad0b1200-b4bb-11eb-99b3-223803ec10f4.png">

**Comment by somtmee** [comment]
This is also the case for the 'contact the operator you travelled with' link on the [Find lost property](https://beta.wmnetwork.co.uk/umbraco/#/content/content/edit/1335) page

**Comment by mrmjprice** [comment]
This is not an error.
