### ISSUE TITLE
inconsistent spacing between text and links in inset text component

### ISSUE THREAD

**Issue by somtmee** [wmcadigital/wmn-cms#128]
## What's wrong?
Too much spacing here between the link and the text above on [Contact National Express](https://beta.wmnetwork.co.uk/umbraco/#/content/content/edit/1583) page. HTML inspector is showing an empty div with a class of 'wmnds-warning-text' between link and text above.

<img width="634" alt="Screenshot 2021-05-14 at 14 12 12" src="https://user-images.githubusercontent.com/68843432/118275494-623ec980-b4be-11eb-9bf0-ccc00a4c6aa7.png">

**Comment by mrmjprice** [comment]
Already fixed by https://github.com/wmcadigital/wmn-cms/issues/105
