### ISSUE TITLE
'Get a disabled person's pass': Inset text component at the bottom has large space between text and link

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#137]
## What's wrong?

Current behaviour:
![image](https://user-images.githubusercontent.com/62507489/118286821-c6678a80-b4ca-11eb-85e3-8d67c3b607cd.png)

There shouldn't be such a large blank space between the address and the email address link

**Comment by mrmjprice** [comment]
Already fixed in next Umbraco release
