### ISSUE TITLE
Incorrect links to Cycle and Walk pages on 'Help someone to apply for Workwise travel support'

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#140]
## What's wrong?

https://beta.wmnetwork.co.uk/swift-and-tickets/discounts-and-free-travel-passes/discounts-for-jobseekers/help-someone-apply-for-workwise-travel-support/

> There are other travel discounts if someone isn’t eligible for Workwise. **Cycling** or **walking** to work or a station also saves money.

Cycling and Walking links under the main heading section directs users to the old website instead of the new pages

**Comment by mrmjprice** [comment]
Thanks
