### ISSUE TITLE
Incorrect links on 'Get a Swift card' page

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#141]
## What's wrong?

https://beta.wmnetwork.co.uk/swift-and-tickets/manage-your-swift-card/get-a-swift-card/

> ## Commuters
> You can load tickets for one week, one month or 52 weeks of travel onto your Swift card. To work out which card is best for you, use our **ticket finder**.
> ...
> If you need to get your card more quickly, you can go to a travel centre or **kiosk** and buy it in person.

Ticket finder link above directs users to the beta homepage.

> ## Commuters
> If you need to get your card more quickly, you can go to a travel centre or **kiosk** and buy it in person.

> ## Pay as you go
> If you need to get your card more quickly, you can go to a travel centre, Payzone store or **kiosk** and buy it in person.

> ## Multi-day tickets
> If you need to get your card more quickly, you can go to a travel centre, Payzone store or **kiosk** and buy it in person.

All of the Kiosk links on the page takes users to the 'Report a problem with Swift' page, instead of: https://beta.wmnetwork.co.uk/get-help/find-a-swift-collector-or-kiosk/

**Comment by mrmjprice** [comment]
Page is being deleted anyway
