### ISSUE TITLE
Anchor tag not working

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-cms#142]
I added anchor next to a link but it doesn't seem to work. 

Issue found on the page 'How to travel with accessibility needs, content card Accessibility on buses, trains and trams. It should take me to opened accordion 'getting around access guide'

https://beta.wmnetwork.co.uk/plan-your-journey/travel-information/how-to-travel-with-accessibility-needs/

**Comment by catiarodriguescosta** [comment]
Yeah, that doesn't work.
I'll try to think in a good way to make it possible. :)

**Comment by catiarodriguescosta** [comment]
This is done now and it is on [dev's environment](https://dev-wmnetwork.s1.umbraco.io/travel-information/how-to-travel-with-accessibility-needs/) but it is case sensitive. Make sure the hashtag is correct. 👍
