### ISSUE TITLE
Links in accordion not rendering properly

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-cms#145]
Issue found on page: Get help if you have a disability or accessibility need > Getting around access guide > PDF

https://beta.wmnetwork.co.uk/plan-your-journey/travel-information/how-to-travel-with-accessibility-needs/get-help-if-you-have-a-disability-or-accessibility-need/

**Comment by mrmjprice** [comment]
Duplicate of the links not rendering in components.
