### ISSUE TITLE
Contact us link is broken

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-cms#146]
Contact us link is broken. Screenshot attached.

<img width="664" alt="Screenshot 2021-05-17 at 09 58 10" src="https://user-images.githubusercontent.com/57525718/118462289-6c4b0d00-b6f6-11eb-994b-5ebde6b28d5d.png">

https://beta.wmnetwork.co.uk/plan-your-journey/travel-information/how-to-travel-with-accessibility-needs/get-help-if-you-have-a-disability-or-accessibility-need/

**Comment by mrmjprice** [comment]
This is the component not rendering the link properly.
