### ISSUE TITLE
Incorrect links on 'Replace a lost or stolen Swift card' page

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#148]
## What's wrong?

https://beta.wmnetwork.co.uk/swift-and-tickets/manage-your-swift-card/replace-a-lost-or-stolen-swift-card/

> Warning component: If you bought your Swift card from National Express, you need to **contact them to replace it**.

Link to contact NX is broken.

> If you’re a Direct Debit Swift card holder you can **replace your lost card online**.

This link takes users to the Make a payment page on the old site. 

> You might be able to **get a refund** if you don’t want a replacement Swift card.

This link doesn't a page hyperlinked.

**Comment by mrmjprice** [comment]
Fixed everything I can, the link not rendering is a known issue
