### ISSUE TITLE
Request an accessibility product Form

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-cms#149]
https://beta.wmnetwork.co.uk/plan-your-journey/travel-information/how-to-travel-with-accessibility-needs/get-help-if-you-have-a-disability-or-accessibility-need/#getting-around-access-guide 

**Issue 1:**

When I fill in info and click ‘continue’, I’m taken back to the top of the page and I need to scroll down to answer the second question. 

This is usability issue because people may get confused because they won't see their form, and they will have to scroll down to see the second question. 

Expected behaviour: when I click ‘continue’, I should se the next form question (bottom of the page), not top of the page. 

<img width="678" alt="Screenshot 2021-05-17 at 10 10 09" src="https://user-images.githubusercontent.com/57525718/118464000-47f03000-b6f8-11eb-9f79-cef13fc1de9c.png">

Issue 2:
What is your address is repeated twice. First time wrong styling is used, the second time correct styling but it is below the content input field. 

<img width="682" alt="Screenshot 2021-05-17 at 10 09 48" src="https://user-images.githubusercontent.com/57525718/118464057-59d1d300-b6f8-11eb-8104-bd39cc15162e.png">

**Comment by mrmjprice** [comment]
Linking back to old form
