### ISSUE TITLE
Content card - link error

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#15]
If you enter a full URL, you get sent to a server error page.
For example: https://beta.wmnetwork.co.uk/umbraco/'https://beta.wmnetwork.co.uk/get-help/contact-us/'

It needs to link to the actual URL.

There also needs to be a local link picker.

<img width="515" alt="Screenshot 2021-02-19 at 10 24 00" src="https://user-images.githubusercontent.com/10854265/108492042-95e1cd00-729c-11eb-8d8f-adae0b3e8e05.png">

**Comment by catiarodriguescosta** [comment]
Fixed! Awaiting the next release to go live!
