### ISSUE TITLE
'Update your Direct Debit contact details' question form issues

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#151]
## Describe the bug

Question content is repeating what is already mentioned in the form label.

The CTA is called 'Next', instead of 'Continue'

When I click on '< Back' on the second question, it requires me to fill in the field even though I want to go back to the first question. Users should be able to go back without having to answer the question on the page they are on.

## Screenshots

![image](https://user-images.githubusercontent.com/62507489/118466651-f72e0680-b6fa-11eb-8f29-78e13a6f6ab2.png)

![image](https://user-images.githubusercontent.com/62507489/118466695-ff864180-b6fa-11eb-9b41-2832ebe71b31.png)

**Comment by mrmjprice** [comment]
Linking back to old form
