### ISSUE TITLE
'Update your concessionary pass details' form

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#155]
## What's wrong?

CTA button text should be 'Continue', instead of 'Next'.

I tried to enter a fake 16-digit card number, for example, 633597 0107 654321 but no error validation appears when I click on the CTA. Not sure if we have swift card number validation but I thought I should raise it just in case.

![Screenshot 2021-05-17 at 11 19 30](https://user-images.githubusercontent.com/62507489/118473343-c3a2aa80-b701-11eb-9009-5928eee8c536.png)

**Comment by mrmjprice** [comment]
Going to just link back to the old site for this.
