### ISSUE TITLE
PDF download issue

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-cms#159]
I cannot open downloaded pdf area map. I download it but when I open I get error message. It looks like faulty pdf is downloaded. The same error occurred with all area maps.

https://beta.wmnetwork.co.uk/plan-your-journey/discover-the-west-midlands/local-area-maps/

<img width="960" alt="Screenshot 2021-05-17 at 11 53 25" src="https://user-images.githubusercontent.com/57525718/118477434-93113f80-b706-11eb-8e7e-aedafe9a24ff.png">

When I open it with acrobat reader, I get this message
<img width="414" alt="Screenshot 2021-05-17 at 11 56 21" src="https://user-images.githubusercontent.com/57525718/118477761-f4391300-b706-11eb-98b0-51be3468f67a.png">

**Comment by mrmjprice** [comment]
https://github.com/wmcadigital/wmn-cms/issues/92
