### ISSUE TITLE
'How to use your Swift card' page: legacy domain link?

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#160]
## What's wrong?

I'm not sure if this is a linking issue, but I thought I'd raise it just in case.

https://beta.wmnetwork.co.uk/swift-and-tickets/manage-your-swift-card/how-to-use-your-swift-card/

> * **use our ticket finder**

This ticket finder links to https://legacy.wmnetwork.co.uk/tickets/#/ which doesn't work.

**Comment by mrmjprice** [comment]
Hello @jkmnch 

Not an issue - this is what we'll do when we link to old apps that haven't been released as a new service.

These are links that could be linked to but don't exist this week:
- https://journeyplanner.tfwm.org.uk
- https://journeyplanner.tfwm.org.uk/operator
- https://legacy.wmnetwork.co.uk/tickets/#/
- https://legacy.wmnetwork.co.uk/timetables/#/
- https://tfwm.org.uk/swift-and-tickets/
- https://my.swiftcard.org.uk
- https://tfwm.org.uk/get-help/report-a-problem-with-a-bus-stop-or-park-and-ride/
- https://tfwm.org.uk/get-help/report-anti-social-behaviour-on-public-transport/
- https://tfwm.org.uk/get-help/
- https://tfwm.org.uk/swift-and-tickets/manage-a-ticket/set-up-cancel-or-update-a-direct-debit/
- https://tfwm.org.uk/swift-and-tickets/manage-your-swift-card/replace-a-lost-or-stolen-swift-card/
- https://tfwm.org.uk/swift-and-tickets/manage-a-ticket/get-a-refund-or-compensation/
- https://tfwm.org.uk/swift-and-tickets/manage-a-ticket/replace-a-lost-or-stolen-ticket-or-pass/
- https://tfwm.org.uk/get-help/request-a-new-bus-shelter-or-stop-pole/
- https://tfwm.org.uk/get-help/find-a-travel-centre/
- https://find-rail-zones.tfwm.org.uk
- https://find-bus-company.tfwm.org.uk
