### ISSUE TITLE
body id of 'majorworks' makes horizontal rules too thick

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#162]
With body id being 'majorworks':
<img width="497" alt="Screenshot 2021-05-18 at 09 29 52" src="https://user-images.githubusercontent.com/10854265/118618508-9b778200-b7bb-11eb-9fdd-cb0292263cb4.png">

Without body id:
<img width="484" alt="Screenshot 2021-05-18 at 09 30 24" src="https://user-images.githubusercontent.com/10854265/118618591-ad592500-b7bb-11eb-8ef2-e041fed9fc6f.png">

**Comment by catiarodriguescosta** [comment]
Good catch! Will try to remove the id without breaking the majorworks page. 👍
