### ISSUE TITLE
Travel updates - current disruptions only / list view

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-cms#165]
Please show disruptions that are happing on the day of viewing the website. Do not show older or future disruptions. 

Also please link to list view by default instead of map view. 

<img width="365" alt="Screenshot 2021-05-18 at 09 52 30" src="https://user-images.githubusercontent.com/57525718/118622073-dd55f780-b7be-11eb-846d-395981015983.png">

**Comment by catiarodriguescosta** [comment]
Hey Kat, this widget is not working yet. this is just an example.
Although Gil has finished it already, I will ask him to show you it working and hopefully, we can merge it. 👍
