### ISSUE TITLE
Add tables from DS into Umbraco

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#168]
[Tables](https://designsystem.tfwm.org.uk/components/table/) will need to be implemented as a usable component in Umbraco

![Screenshot 2021-05-19 at 14 23 08](https://user-images.githubusercontent.com/62507489/118819970-bfb38b80-b8ad-11eb-9e40-e53bf0bc131a.png)

Users will need to be able to edit rows, columns and cell content within Umbraco.

Tables will also need to be able to fit within accordions. This is for the [Swift Go capping page](https://www.figma.com/file/PDLwmCZgpcrI6hfIHKYLku/New-Swift-Custom-Pages?node-id=0%3A1)

This is a should have. It is important to have this built for the Swift Go capping page, but it can wait. We may go live just with a simple grid table if we run out of time.

**Comment by catiarodriguescosta** [comment]
Tables are available inside RTE (in the toolbar there is an option to table). 
They are styled as they are on the design system. :) 
Reopen it if you do not find them, please.

Note: in the backoffice they are not equal to design system cause you should see the cells borders. But after save it should display correctly.

**Comment by mrmjprice** [comment]
Hi Catia, do we have the ability to show them in accordions?

**Comment by catiarodriguescosta** [comment]
**A few instructions to create a table with header**
> By default all rows of the table are from body, if you want to have a table header you need to select the first row, go to the table icon on the toolbar, select ''Row" > "Row Properties" and change Row type to "Header". Save it and it must assume the correct style (complete different approach on small screens).

**Comment by catiarodriguescosta** [comment]
> Hi Catia, do we have the ability to show them in accordions?

Yes, it should work there too. Not sure if the icon is available there, if not I can add it. And we can test it.

**Comment by KaterinaKir** [comment]
@catiarodriguescosta  thank you for letting us know. I created a mock up table here. It looks great on the desktop, but mobile view doesn't seem to work well. https://beta.wmnetwork.co.uk/content-playground/ 
<img width="655" alt="Screenshot 2021-05-19 at 14 44 58" src="https://user-images.githubusercontent.com/57525718/118823312-cee80880-b8b0-11eb-8a9c-a678a52f8a91.png">
<img width="499" alt="Screenshot 2021-05-19 at 14 45 46" src="https://user-images.githubusercontent.com/57525718/118823482-eb844080-b8b0-11eb-8dc4-4d27ca91bda7.png">

**Comment by KaterinaKir** [comment]
@catiarodriguescosta Also I cannot see option in RTE to add a table in accordion. Please advise. 
<img width="871" alt="Screenshot 2021-05-19 at 14 43 53" src="https://user-images.githubusercontent.com/57525718/118823577-fc34b680-b8b0-11eb-8921-5a1c033a6e13.png">

**Comment by jkmnch** [comment]
I can add tables in accordions by copying & pasting the table into the accordion body content text area, but this causes the show/hide accordion icons to disappear (not sure if this is an issue with the page in general as they don't appear for any other accordions)

![Screenshot 2021-05-19 at 15 00 23](https://user-images.githubusercontent.com/62507489/118825843-f17b2100-b8b2-11eb-9e86-91605f44a389.png)

**Comment by catiarodriguescosta** [comment]
So I've enabled the tables inside the RTE all components (not only accordion) and I've fixed the bug with table on mobile.
@jkmnch not sure why it was causing issues, but it's better to use the table icon cause we are treating this table as ours and we do have a js code to transform the table into a new version to be displayed on mobile.
