### ISSUE TITLE
Plan a journey and buy a ticket widgets should use tabs in mobile view

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#178]
## What
> The Plan a journey and Buy a ticket homepage widgets should be tabbed when the homepage is viewed on a mobile.
>
> Not sure if this change should be raised in the DS or CMS projects. Feel free to move it if necessary.

## Why
> Hiding the Plan a journey and Buy a ticket widgets behind a tab will reduce the page height on mobile.

![Screenshot 2021-05-18 at 10 25 29](https://user-images.githubusercontent.com/62507489/118627158-61aa7980-b7c3-11eb-9aa8-b62e9ba46b09.png)

## Anything else
> Default view on mobile: https://zpl.io/257qppn
> Buy a ticket selected on mobile: https://zpl.io/Vq3rLp5
>
> Happy to have a call to discuss this further.

**Comment by catiarodriguescosta** [comment]
This is deployed on the dev's environment: https://dev-wmnetwork.s1.umbraco.io/
Will be live this Thursday. :)
