### ISSUE TITLE
3-col grid, content cards are not even

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#183]
<img width="1029" alt="Screenshot 2021-06-08 at 08 20 55" src="https://user-images.githubusercontent.com/10854265/121141057-74e4be00-c832-11eb-89b1-2db6eb358e1a.png">

Example: https://beta.wmnetwork.co.uk/swift-and-tickets/

**Comment by daylesalmon** [comment]
Do they all need to be the same height @mrmjprice ?

**Comment by mrmjprice** [comment]
Yes please, this is how it is handled on the 2-col grid :)

**Comment by mrmjprice** [comment]
Just noticed that it's not doing it anywhere again.

**Comment by catiarodriguescosta** [comment]
Oh noo.. :(
going to have a look now.

**Comment by catiarodriguescosta** [comment]
It's fixed! 👍
