### ISSUE TITLE
"Request an accessible format" link goes nowhere

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#188]
Should go to contact us page.

**Comment by catiarodriguescosta** [comment]
Can you paste an example where that happens? 
Maybe that was happening when using macro, if so, you need to replace it with a file download component.

**Comment by mrmjprice** [comment]
I hope it's not as I've just made about 60 of them 🤭

https://beta.wmnetwork.co.uk/who-we-are/our-strategy/network-resilience-keeping-transport-moving/key-route-network/

**Comment by catiarodriguescosta** [comment]
It seems to be working on dev.
Needs to be double-checked after today's release.
