### ISSUE TITLE
Add a new image resize option for banner images

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#189]
![Screenshot 2021-06-09 at 10 53 55](https://user-images.githubusercontent.com/62507489/121334101-4be72a80-c911-11eb-82f3-b2808fbc803e.png)

At present, content editors can only resize images for content cards. There needs to be a new option for content editors to resize images for Page banners.

This image size needs to the 100% width and 325px high.

**Comment by mrmjprice** [comment]
While we're here, can we have one for the homepage banner too please?

**Comment by mrmjprice** [comment]
* Just over half page - https://beta.wmnetwork.co.uk/plan-your-journey/ways-to-travel/walking-in-the-west-midlands/
* Full-width - https://beta.wmnetwork.co.uk/plan-your-journey/ways-to-travel/
* Full-width (home) - https://beta.wmnetwork.co.uk

**Comment by daylesalmon** [comment]
This is now complete
