### ISSUE TITLE
Add HTML editor to accordion content

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#192]
We need to be able to use table headers for columns and rows to make tables accessible.

For Key Route Network pages, I had to edit the HTML to use ```<th>``` and header roles. It doesn't look like Umbraco's table editor lets you do this.

<img width="1039" alt="Screenshot 2021-06-11 at 08 47 31" src="https://user-images.githubusercontent.com/10854265/121650739-c76fe580-ca91-11eb-8c29-084c9b91538d.png">

**Comment by catiarodriguescosta** [comment]
Will close this one.
But it stays note here: **If you have a table, to define the header, select the first row and go to table > Row > Row properties and change it to header.**
