### ISSUE TITLE
Homepage timetable widget: Bus service field not showing autocomplete

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#200]
## Describe the bug
Autocomplete is not working in the bus service field of the homepage 'Find a timetable' widget.

When I manually enter a service number and click enter on my keyboard, nothing is returned on the results page (even though bus services with the number exist). 

## Screenshots
<img width="464" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/62507489/122013110-c56d9580-cdb5-11eb-936e-5cbede970b6e.png">

![Screenshot 2021-06-15 at 08 45 33](https://user-images.githubusercontent.com/62507489/122013414-0fef1200-cdb6-11eb-8615-c87f237b2bdd.png)

**Comment by catiarodriguescosta** [comment]
hmm... Actually didn't realize it would be an autocomplete. It's not on the old design but this can be a thing to improve. 👍 
Will change the tags and prioritize the bugs. 👍

**Comment by jkmnch** [comment]
Hi Catia, I always had thought that it used autocomplete. But I may have been getting confused with the plan your journey widget. 

Autocomplete would be a nice to have, but for now, we would need to add a 'Find timetable' CTA button below the service number field. So users aren't relying on the enter key on their keyboard to submit the search. Is this something that could be done? This would have higher priority than autocomplete

**Comment by catiarodriguescosta** [comment]
Yeah, that can be done with no problem! 👍

**Comment by catiarodriguescosta** [comment]
It's implemented here: https://staging.tfwm.org.uk/
Do you want to remain this open for the autocomplete?

<img width="495" alt="Screenshot 2021-06-15 at 15 48 44" src="https://user-images.githubusercontent.com/34938764/122075810-4185ce80-cdf2-11eb-9eff-cf4fd8f843bc.png">

**Comment by jkmnch** [comment]
We're no longer going to add an autocomplete for the bus service field, as some bus service numbers can return a lot of results (25 for bus service no.7 for example). This is going to make the autocomplete difficult to use for the user, especially on mobile.

The current functionality (with the new CTA button added) is fine.
