### ISSUE TITLE
Timetables: Page isn't returning any bus or tram results

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#201]
## Describe the bug
The Timetables page isn't returning any bus services when a user searches for one and the MM1 service doesn't appear when the user clicks on tram.

## Screenshots
![Screenshot 2021-06-15 at 08 51 16](https://user-images.githubusercontent.com/62507489/122014226-dc60b780-cdb6-11eb-835a-654b2869112d.png)

![Screenshot 2021-06-15 at 08 52 26](https://user-images.githubusercontent.com/62507489/122014389-05814800-cdb7-11eb-9e71-a2e644a7f738.png)

**Comment by catiarodriguescosta** [comment]
CORS issue on the old ticket finder.
@Rippled will have a look.

**Comment by catiarodriguescosta** [comment]
CORS issue is sorted! 👍
