### ISSUE TITLE
Mobile nav: Extend clickable area

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#202]
## What's wrong?
The mobile navigation clickable area needs to be expanded to cover the nav titles. Currently, the only clickable area is the Chevron icon and some users are getting confused thinking the links aren't working.

![Screenshot 2021-06-15 at 08 54 49](https://user-images.githubusercontent.com/62507489/122016417-f1d6e100-cdb8-11eb-805f-7bf297693a95.png)

I've raised this as a DS issue here: https://github.com/wmcadigital/wmn-design-system/issues/819

**Comment by catiarodriguescosta** [comment]
On staging now: 
https://staging.tfwm.org.uk/

**Comment by jkmnch** [comment]
Hey Catia, can this also be enabled for Level 2 links that have dropdowns within them? As I still need to click on the Chevron for the L3 links to show.

![Screenshot 2021-06-16 at 15 02 20](https://user-images.githubusercontent.com/62507489/122233462-fe8c2f80-ceb3-11eb-997e-1640203c4078.png)

**Comment by catiarodriguescosta** [comment]
Oh, you're right! 
It's updated now: https://staging.tfwm.org.uk/

**Comment by jkmnch** [comment]
Hey Catia, I've just had a look at the new mobile nav and I've noticed a potential issue.

For level 2 links which have a dropdown for level 3 links and where the page title itself is a hub page, it takes users to the hub page instead (whilst showing the dropdown for about 1 second). 

I think for the level 2 links that have a hub page and have level 3 links underneath it, we should hide the L3 links from appearing when the area is clicked, but show the dropdown with level 3 links when only the Chevron is clicked.

Hopefully, this makes sense. Let me know if you want to discuss it over a call.

**Comment by catiarodriguescosta** [comment]
Hey, that issue was fixed before my holidays and it went live in the last week release. 👍
