### ISSUE TITLE
Journey planer sidebar widget arrival time link broken

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#212]
## Describe the bug
The arrival time link in the journey planner widget doesn't change to arrival time. The link should change from leave time to arrival time.

## Where is this happening?
I've published the widget on the hospital page to test it: https://www.tfwm.org.uk/plan-your-journey/travel-information/how-to-get-to-a-hospital/

## Screenshots
<img width="519" alt="Screenshot 2021-06-21 at 09 10 23" src="https://user-images.githubusercontent.com/62507489/122731206-f432b280-d272-11eb-958a-e3792f1fb45f.png">

## Additional context
Original arrival time design in Zeplin: https://zpl.io/V1Ewn8B

**Comment by catiarodriguescosta** [comment]
This is now fixed on staging: https://staging.tfwm.org.uk/
Not sure when it will go live, probably this Thursday or in the next one. 👍
