### ISSUE TITLE
tfwm.org.uk domain not being tracked in Google Analytics

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#213]
## Describe the bug
I'm not sure if this is a CMS bug, or if this is reliant on the Marketing team to fix, but the new tfwm.org.uk domain isn't being tracked in Google Analytics

## Where is this happening?
GA tracks tfwm.org.uk subdomains and legacy.wmnetwork.co.uk domains, but not the actual tfwm.org.uk domain.

## Screenshots

From the realtime stats data on the dashboard
<img width="762" alt="Screenshot 2021-06-21 at 13 36 41" src="https://user-images.githubusercontent.com/62507489/122763003-c9a62100-d295-11eb-9824-091be54a5b03.png">

**Comment by catiarodriguescosta** [comment]
To be tested again after the go live.
