### ISSUE TITLE
Content editors can add transport modal icons to Swift product page banners

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#214]
Figma file: https://www.figma.com/file/PDLwmCZgpcrI6hfIHKYLku/New-Swift-Custom-Pages?node-id=515%3A373

There has been a request from the Swift team to add coloured transport mode icons in the purple Swift product page banner. We have designed what the new banner should look like and Swift are happy to proceed. 

Some transport modes are only applicable to certain Swift products, therefore content editors must be able to manually choose which transport icons they want to show in the back office (maybe a checkbox for each transport modal icon?).

The current transport modal icons which need to be added are (in order):
- Bus
- Train
- Tram
- Park and ride

The Park and ride default modal icon colour is Primary Purple, so we've added a 1px white border to make it stand out from the background.

**Comment by catiarodriguescosta** [comment]
Umbraco updates are done in this branch: cc/feature/purple-banner-with-transport-modals
Awaiting for the next design system release in order to have the correct styling of transport modals.
