### ISSUE TITLE
wmnetwork.co.uk/cyclepod redirect needs changing

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#215]
## What's wrong?
www.wmnetwork.co.uk/cyclepod should go to https://www.tfwm.org.uk/plan-your-journey/ways-to-travel/cycling-in-the-west-midlands/find-bike-storage-at-a-station/ not the old legacy application page.

I tried changing the redirect in the old Umbraco to a URL and the legacy find bike storage page (to then redirect it again to the new site), but this doesn't work.

<img width="993" alt="Screenshot 2021-06-22 at 09 10 15" src="https://user-images.githubusercontent.com/62507489/122888344-acc32980-d339-11eb-92b1-8eb5d6230cc6.png">

**Comment by daylesalmon** [comment]
Hi @jkmnch, 

This is now fixed. 

The issue was that wmnetwork.co.uk/cyclepod is the same as tfwm.org.uk/cyclepod so you need to update the redirect on the TfWM Umbraco. Only legacy.wmnetwork.co.uk links you need to edit on the old Umbraco.

Hope that helps :)
