### ISSUE TITLE
Embedding a YouTube video disappears after save

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#216]
## Describe the bug
I'm trying to embed a Youtube video on this page: https://www.tfwm.org.uk/plan-your-journey/ways-to-travel/cycling-in-the-west-midlands/find-bike-storage-at-a-station/

The YouTube video can be added through the Embed link in the text editor, however, the video disappears when I save or publish the page.

Youtube video link I'm using in the embed field: https://youtu.be/4gWwl0yqgO0

**Comment by catiarodriguescosta** [comment]
Hey @jkmnch,
Video is now on the page: https://www.tfwm.org.uk/plan-your-journey/ways-to-travel/cycling-in-the-west-midlands/find-bike-storage-at-a-station/
You might need to amend the copy.
Let me know if you are happy with that solution or if you want it bigger, for instance.
Thanks

**Comment by jkmnch** [comment]
Hey Catia, thanks for adding the video in

Was this embed issue just this single page? or across the whole Umbraco?
