### ISSUE TITLE
Users can't access disruptions service from WMCA corporate connection

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#217]
## Describe the bug
We've had a bug report come through that a user cannot access the dirsuptions.tfwm.org.uk service from the WMCA internal servers.

## Screenshots
![imgpsh_mobile_save](https://user-images.githubusercontent.com/62507489/122914679-cde44400-d352-11eb-8cfd-9419f9703da7.jpg)
![b8d83bc2-e9b7-422e-9fe2-7e1f3864cd76](https://user-images.githubusercontent.com/62507489/122914695-d0469e00-d352-11eb-834b-764ff26c08c2.jpg)

**Comment by daylesalmon** [comment]
Closing as this is an internal DNS/firewall issue.
