### ISSUE TITLE
TfWM logo size

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-cms#219]
TfWM logo looks smaller on disruptions, timetable and ticketing app. 

Correct size on the homepage
<img width="1033" alt="Screenshot 2021-06-30 at 13 08 33" src="https://user-images.githubusercontent.com/57525718/123958047-7f632500-d9a4-11eb-9528-332b37aa4c84.png">

Smaller on disruptions app
<img width="1051" alt="Screenshot 2021-06-30 at 13 09 44" src="https://user-images.githubusercontent.com/57525718/123958081-8b4ee700-d9a4-11eb-82e9-2d34ffc8c078.png">

Smaller on timetables app

<img width="1068" alt="Screenshot 2021-06-30 at 13 11 39" src="https://user-images.githubusercontent.com/57525718/123958282-c4875700-d9a4-11eb-9966-24783e55e3d9.png">

Smaller on ticketing app
<img width="1096" alt="Screenshot 2021-06-30 at 13 12 33" src="https://user-images.githubusercontent.com/57525718/123958358-dd900800-d9a4-11eb-9ac0-0b49ad309f48.png">

**Comment by catiarodriguescosta** [comment]
I will close this one as it it repeated: #204
