### ISSUE TITLE
Add a visual divide between "Banner Image" and grid editor

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#22]
<img width="1248" alt="Screenshot 2021-02-19 at 10 51 21" src="https://user-images.githubusercontent.com/10854265/108495204-67fe8780-72a0-11eb-986a-6252e2b1afe2.png">

**Comment by catiarodriguescosta** [comment]
Fixed on localhost!
Happy with it?

<img width="1393" alt="Screenshot 2021-02-19 at 12 47 57" src="https://user-images.githubusercontent.com/34938764/108506484-c59ad000-72b0-11eb-82db-5b14c9d63bc2.png">

**Comment by mrmjprice** [comment]
Yes, thank you 😃

**Comment by mrmjprice** [comment]
Replace with #25
