### ISSUE TITLE
Stay up to date widget 

### ISSUE THREAD

**Issue by RachelFoy** [wmcadigital/wmn-cms#222]
Can the copy be made editable - when we add a unique link in we need to be able to change the copy

**Comment by catiarodriguescosta** [comment]
Hi Rachel, 
This is on staging now: https://staging.tfwm.org.uk/
Thursday I will be pushing this live. So let me know if you are happy with it. ;)

![image](https://user-images.githubusercontent.com/34938764/124472306-de0a1380-dd95-11eb-88cc-b21153f50c8e.png)

Thanks,
Catia Costa
