### ISSUE TITLE
New link to update concessionary travel pass details gives 404

### ISSUE THREAD

**Issue by somtmee** [wmcadigital/wmn-cms#224]
We're linking to this link from somewhere on the site: [https://www.tfwm.org.uk/tickets-and-passes/older-persons-pass/update-your-concessionary-travel-pass-details/](https://www.tfwm.org.uk/tickets-and-passes/older-persons-pass/update-your-concessionary-travel-pass-details/)

This gives a 404. 

This new link needs to be forwarded to [https://legacy.wmnetwork.co.uk/forms/concessionary-updates/](https://legacy.wmnetwork.co.uk/forms/concessionary-updates/)

**Comment by catiarodriguescosta** [comment]
@somtmee, this now fixed.
Thank you!
