### ISSUE TITLE
Button disappears

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#23]
If you add a button as a macro, it disappears:
- It doesn't render in the content block
- Doesn't publish

**Comment by catiarodriguescosta** [comment]
This is a umbraco bug.... 
After creating the button, click over the RTE (give an enter for example) and save it.
I know this is awful.... so sorry... Trying to reach umbraco cause of these kind of bugs.. hope they can do something to fix it...

**Comment by mrmjprice** [comment]
Thank you @catiarodriguescosta - I've just tried this and it works.

# Interim fix

1. Add button
2. Click into the content block editor
3. Hit enter
4. Press save
5. Go back and remove the line break you added
6. Press save again

**Comment by catiarodriguescosta** [comment]
Probably it works without the enter part. I read that you just need to click out the macro, inside RTE, after the creation to have it working...

**Comment by catiarodriguescosta** [comment]
https://github.com/umbraco/Umbraco-CMS/issues/9874
They have replied... but for now we need to keep using that trick (to click after the creation inside RTE)
