### ISSUE TITLE
Make grid & banner within the "Content" tab of a content node neater

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#25]
Follow Matryoshka way of implementing, so there are sections:

**Banner**
((Banner Image))

**Content**
((Grid))

**Comment by catiarodriguescosta** [comment]
<img width="1387" alt="Screenshot 2021-02-19 at 14 27 26" src="https://user-images.githubusercontent.com/34938764/108516865-a1de8680-72be-11eb-8719-9b5e04112681.png">
