### ISSUE TITLE
Rich text editor - Formatting dropdown not working in Safari

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#26]
Can only select Inset text.

<img width="392" alt="Screenshot 2021-02-23 at 10 18 15" src="https://user-images.githubusercontent.com/10854265/108829743-74485480-75c0-11eb-942b-fa9b761d2551.png">

**Comment by catiarodriguescosta** [comment]
It's fixed and it was happening everywhere. :)
I've done it before the demo but it's not live yet..
