### ISSUE TITLE
Rich text editor - Change Macro icon from cogs to +

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#27]
Icon is confusing as it looks like settings.

**Comment by mrmjprice** [comment]
```icon-add```

**Comment by catiarodriguescosta** [comment]
<img width="657" alt="Screenshot 2021-02-23 at 16 57 31" src="https://user-images.githubusercontent.com/34938764/108878539-41ba4e00-75f8-11eb-8787-b56130589117.png">
