### ISSUE TITLE
Rich text editor - Background should be background grey colour, not white

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#28]
<img width="743" alt="Screenshot 2021-02-23 at 10 20 01" src="https://user-images.githubusercontent.com/10854265/108829941-b2de0f00-75c0-11eb-875c-2499eb291cd9.png">

**Comment by catiarodriguescosta** [comment]
<img width="685" alt="Screenshot 2021-02-23 at 17 10 44" src="https://user-images.githubusercontent.com/34938764/108880465-39631280-75fa-11eb-97b4-9dc8586845cc.png">

On edition (opened):
<img width="675" alt="Screenshot 2021-02-23 at 17 10 17" src="https://user-images.githubusercontent.com/34938764/108880459-3831e580-75fa-11eb-97ec-a95dee33e45e.png">
