### ISSUE TITLE
Rich text editor - Numbered items in format menu

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#29]
<img width="372" alt="Screenshot 2021-02-23 at 10 20 41" src="https://user-images.githubusercontent.com/10854265/108830023-cab59300-75c0-11eb-9db0-2c50c140408e.png">

Should this be in the numbered list menu?

**Comment by catiarodriguescosta** [comment]
I didn't find a way to add it to the numbered list options, Dayle agreed with this solution. However, I did remove the list of options of each list but when we did the umbraco upgrade, the change was gone. I will try to remove those options permanently and will give you feedback here.
Thanks.

**Comment by catiarodriguescosta** [comment]
Those carets are now gone, and they might be gone after Umbraco upgrades.
