### ISSUE TITLE
RTE 'Select macro' icons

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#30]
<img width="502" alt="Screenshot 2021-02-23 at 10 21 53" src="https://user-images.githubusercontent.com/10854265/108830157-f59fe700-75c0-11eb-9773-f9bc837fcfb7.png">

Change to those below...

**Comment by mrmjprice** [comment]
Warning text - ```icon-alert```

**Comment by mrmjprice** [comment]
File download - ```icon-documents```

**Comment by mrmjprice** [comment]
File download - ```icon-autofill```

**Comment by mrmjprice** [comment]
Button - ```icon-hand-pointer-alt```

**Comment by mrmjprice** [comment]
Detials - ```icon-indent```

**Comment by catiarodriguescosta** [comment]
<img width="484" alt="Screenshot 2021-02-23 at 15 07 05" src="https://user-images.githubusercontent.com/34938764/108863196-d9b03b80-75e8-11eb-8f58-d74e185564cb.png">
