### ISSUE TITLE
Page layout - switch between left/right/no sidebar

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#31]
Currently, you can't switch layouts once you've chosen one.

**Comment by catiarodriguescosta** [comment]
I'm afraid you need to remove all the content, change the layout and insert content again. :/
[https://our.umbraco.com/forum/using/ui-questions/61541-How-to-change-Grid-Layout#comment-209222](https://our.umbraco.com/forum/using/ui-questions/61541-How-to-change-Grid-Layout#comment-209222)

**Comment by mrmjprice** [comment]
Can we tell the user this when the user is choosing a layout?

"You cannot change the type of layout later"

<img width="539" alt="Screenshot 2021-03-04 at 13 58 59" src="https://user-images.githubusercontent.com/10854265/109974743-c80a1a80-7cf1-11eb-855c-ad02493e12c7.png">

**Comment by mrmjprice** [comment]
cc @somtmee @KaterinaKir @jkmnch for the copy ideas?

You cannot change a layout once you have chosen it.

**Comment by jkmnch** [comment]
Some copy ideas:
- You cannot change the layout after you've chosen it.
- Choose the right layout for your page. You cannot change it later.
- You cannot change the layout later. If you want to change it, you'll need to create a new page.

I think we might need to include that part where if they want to change it after, they'll need to create a new page.

**Comment by somtmee** [comment]
I like that suggestion Jake.
 
How about a hybrid of the last two:
 
**Choose a layout**
You cannot change this once the page published. If you want to change the layout you’ll need to create a new page.
 
This only really works if you can have a subheading. Way too long if not

**Comment by somtmee** [comment]
I like that suggestion Jake.

How about a hybrid of the last two:

Choose a layout
You cannot change this once the page published. If you want to change the layout you’ll need to create a new page.

This only really works if you can have a subheading. Way too long if not

--
Tom Smee
User Researcher

Our organisation is working flexibly, so if you’ve received this email ‘out of hours’, whilst it suits me to email now, I do not expect a response or action outside of your working hours.

Email: tom.smee@wmca.org.uk<mailto:tom.smee@wmca.org.uk>
Website: www.wmca.org.uk<http://www.wmca.org.uk/> 

[cidimage001.png@01D55835.63950840]<http://www.wmca.org.uk/> 
Building a more prosperous West Midlands
16 Summer Lane, Birmingham, B19 3SD

The views expressed in this email are those of the sender and do not reflect the views of West Midlands Combined Authority.


Confidentiality: The information in this email may be confidential, contain personal and/or sensitive information, and/or may be legally privileged. If an addressing or transmission error has misdirected this email, please notify the author by replying to this email and then deleting the original and your reply. If you have received this email in error, any disclosure, copying, distribution, or any action taken or omitted to be taken in reliance on the email, may be prohibited and potentially unlawful

Find out about WMCA by visiting https://www.wmca.org.uk<https://www.wmca.org.uk/>
[cid:image002.jpg@01D7110B.5CD1BA40]Please consider the environment before printing this email.

**Comment by mrmjprice** [comment]
How about we just go with

**Choose a layout**
You cannot change this later

**Comment by somtmee** [comment]
Sure! If there's time to do it at some point down the line, it might be good to preference test that version with one where we reference what the user needs to do if they want to change layout. My assumption is that they might want to know that rather than infer it

**Comment by catiarodriguescosta** [comment]
Updated it to:

**Choose a layout**
You cannot change this later
