### ISSUE TITLE
Copy the page contents component from WMCA CMS

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#33]
Use inline navigation content card - https://designsystem.wmnetwork.co.uk/patterns/content-cards/

Populate using H2s and H3s

**Comment by catiarodriguescosta** [comment]
**Actions**:
[ ] Create a new component for In-line navigation card that will work for In-line navigation with current page too. [https://designsystem.wmnetwork.co.uk/patterns/content-cards/](https://designsystem.wmnetwork.co.uk/patterns/content-cards/)

This will be using the new editor service, so can't be done right now. But as soon as we have all the components updated (with the new editor service), this one will be created.

**Comment by catiarodriguescosta** [comment]
Backoffice:
<img width="1438" alt="Screenshot 2021-03-11 at 13 41 13" src="https://user-images.githubusercontent.com/34938764/110796071-77ee0380-826f-11eb-9201-4b1bdf33557b.png">

Rendered version:
<img width="1178" alt="Screenshot 2021-03-11 at 13 39 05" src="https://user-images.githubusercontent.com/34938764/110795897-407f5700-826f-11eb-8f3e-249bb0e318ae.png">

**Comment by catiarodriguescosta** [comment]
<img width="1025" alt="Screenshot 2021-03-15 at 12 49 56" src="https://user-images.githubusercontent.com/34938764/111155919-01ae1180-858d-11eb-8ff5-f7b987548eeb.png">
 Update:

- It allows editor to change the links appearance (link as button, if that's the case).
- Automatically generate the page contents (h2 and h3 inside block content.) - and hyperlink to that section of the page
- Allow editor to create their own navigation card (with title editable and links editable)
