### ISSUE TITLE
Change "Card w/ Code" name and icon

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#34]
- Name: Developer Card
- Icon: Spanner

**Comment by mrmjprice** [comment]
<img width="633" alt="Screenshot 2021-02-23 at 10 32 09" src="https://user-images.githubusercontent.com/10854265/108831695-6562a180-75c2-11eb-9bc4-550ded32faf4.png">

**Comment by catiarodriguescosta** [comment]
This is the list of all available icons:
https://nicbell.github.io/ucreate/icons.html

Could you have a look, please? :)
I will use this one for now: _icon-umb-developer_! 
Let me know which one is your favourite for this purpose!

**Comment by mrmjprice** [comment]
I think ```icon-sandbox-toys``` gives the best impression that it's something for devs/playing around

**Comment by mrmjprice** [comment]
Probably ```icon-info``` for Message too

**Comment by catiarodriguescosta** [comment]
<img width="648" alt="Screenshot 2021-02-23 at 15 19 59" src="https://user-images.githubusercontent.com/34938764/108865017-a53d7f00-75ea-11eb-97cf-0531940302e4.png">

The 2 components were updated! :)
Reopen if you need any other update.
