### ISSUE TITLE
Content card not flush when used in a row

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#35]
<img width="705" alt="Screenshot 2021-02-23 at 10 32 51" src="https://user-images.githubusercontent.com/10854265/108831759-7d3a2580-75c2-11eb-9c7d-07b2bedd4804.png">

They should both be the same height

**Comment by catiarodriguescosta** [comment]
Page link to [test](https://beta.wmnetwork.co.uk/resources-and-support/resources-and-support-for-education-providers/workshop-resources-for-journey-planning/).

**Comment by catiarodriguescosta** [comment]
This is now fixed but there are rules.

- If you want to have 2 content cards side by side with same height you must create a 2 columns row and add *one* content card to each column.
<img width="711" alt="Screenshot 2021-03-18 at 14 07 22" src="https://user-images.githubusercontent.com/34938764/111640222-e7c23800-87f3-11eb-8391-a8f7edec2acc.png">
<img width="757" alt="Screenshot 2021-03-18 at 14 10 43" src="https://user-images.githubusercontent.com/34938764/111640271-f3156380-87f3-11eb-97d4-e84ea38ea5d3.png">


- If you add more than one content card to one of the columns, the column with one element will have the height of the other column. See image below.
<img width="720" alt="Screenshot 2021-03-18 at 14 09 42" src="https://user-images.githubusercontent.com/34938764/111640604-3f60a380-87f4-11eb-8ef2-2019f29d7323.png">
<img width="698" alt="Screenshot 2021-03-18 at 14 11 14" src="https://user-images.githubusercontent.com/34938764/111640632-45568480-87f4-11eb-8f0d-8a565f4b50ba.png">


- If you add more than one content card to both columns, they will appear but their height will be relative (not related with the other column)
<img width="710" alt="Screenshot 2021-03-18 at 14 16 28" src="https://user-images.githubusercontent.com/34938764/111641045-ada56600-87f4-11eb-886b-b6089a5a0d59.png">
<img width="742" alt="Screenshot 2021-03-18 at 14 17 03" src="https://user-images.githubusercontent.com/34938764/111641047-ae3dfc80-87f4-11eb-9bb4-29e78c37af42.png">


Let me know if you have any doubts about it!!
:)
