### ISSUE TITLE
Content card / accordions - can we auto-generate IDs?

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#37]
Can we make this automatic, using the title?

Otherwise, we need to educate content editors.

<img width="512" alt="Screenshot 2021-02-23 at 10 35 18" src="https://user-images.githubusercontent.com/10854265/108832009-d5712780-75c2-11eb-80c8-8b3608c71ea0.png">

**Comment by catiarodriguescosta** [comment]
Both accordion and cards (navigation card, content card, developer card) have an automatic id.
