### ISSUE TITLE
Banner image

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#39]
- [x] Needs a height of 325px
- [x] Should hide on mobile
- [x] Add help text/description for banner image - "Does not show for mobile users"

**Comment by catiarodriguescosta** [comment]
@daylesalmon Do you want this class to be part of the Design system?
I opt by a background approach, used a div with background image (cover, centered), and used the page title as the title attribute.

**Comment by mrmjprice** [comment]
Yes, that approach sounds good to me.

Not sure about needing it on the design system.
