### ISSUE TITLE
Implement travel mode page banner

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#40]
https://designsystem.wmnetwork.co.uk/patterns/banner/#travel-mode-page-banner

**Comment by catiarodriguescosta** [comment]
**Editor controls:**
mode
image
content

**Editor can't control:**
mode icon
logos of mode
colour of mode

backoffice
<img width="1437" alt="Screenshot 2021-03-18 at 11 14 45" src="https://user-images.githubusercontent.com/34938764/111617761-724a6d80-87db-11eb-946f-950edbbee1a8.png">

frontend
<img width="1435" alt="Screenshot 2021-03-18 at 11 15 01" src="https://user-images.githubusercontent.com/34938764/111617765-737b9a80-87db-11eb-9f70-1b62a1bf33ab.png">
