### ISSUE TITLE
Grid - Should the reorder bar be a different colour?

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#42]
Should this be primary purple? Looks strange at the moment.

<img width="1181" alt="Screenshot 2021-02-23 at 10 39 01" src="https://user-images.githubusercontent.com/10854265/108832362-592b1400-75c3-11eb-9fe5-34602fc9aed8.png">

**Comment by catiarodriguescosta** [comment]
@mrmjprice Does it looks good to you?
<img width="1043" alt="Screenshot 2021-02-23 at 13 05 50" src="https://user-images.githubusercontent.com/34938764/108847671-e24c4600-75d7-11eb-9524-3fdacae80d4f.png">

**Comment by mrmjprice** [comment]
Hey Catia, I talked w/ Design about this.

- [ ] Change "Content" section header to primary purple
- [ ] Change Reorder bar to secondary purple

If possible:
- [ ] Change "Reorder" to "Move content blocks"
- [ ] Change "I am done reordering" to "Save content blocks"

**Comment by catiarodriguescosta** [comment]
<img width="1438" alt="Screenshot 2021-02-23 at 16 18 15" src="https://user-images.githubusercontent.com/34938764/108873436-09644100-75f3-11eb-885a-6b08d66f58d4.png">
<img width="1050" alt="Screenshot 2021-02-23 at 16 18 38" src="https://user-images.githubusercontent.com/34938764/108873444-0b2e0480-75f3-11eb-8dc2-529c89e9b8ae.png">

Please reopen it if you want to do any other changes! 👍
