### ISSUE TITLE
Forms - Conditional questions don't appear

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#47]
https://beta.wmnetwork.co.uk/get-help/contact-us/

If you select "A bus or travel pass", a reference number field should appear. It doesn't. 😢

**Comment by catiarodriguescosta** [comment]
It's fixed now.. I was missing the form dependencies.
I did a form to test conditional questions on my localhost and it's working fine! It will be fixed for you after the next release! :)
