### ISSUE TITLE
Forms - Question has incorrect styling

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#48]
I'm not clear in the "right" way to create a form in Umbraco to make it appear "right" on the front-end.

<img width="664" alt="Screenshot 2021-02-24 at 08 52 26" src="https://user-images.githubusercontent.com/10854265/108974709-9fdd4480-767d-11eb-9fff-8018e8cd7aed.png">

**Comment by catiarodriguescosta** [comment]
Hey @mrmjprice, the default title of a form field behaves as a label. If you want to have big purple title (h2) you need to create a new field named "Title and description".

<img width="817" alt="Screenshot 2021-03-02 at 11 03 50" src="https://user-images.githubusercontent.com/34938764/109639582-44acc580-7b47-11eb-8611-4522cd1c25f5.png">

Please, reopen it if you need to clarify anything else.
