### ISSUE TITLE
Visual bug - file download component alignment

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#49]
<img width="562" alt="Screenshot 2021-02-25 at 11 07 21" src="https://user-images.githubusercontent.com/10854265/109144918-b8229180-7759-11eb-8c00-b01d5553eb9c.png">

<img width="562" alt="Screenshot 2021-02-25 at 11 07 21" src="https://user-images.githubusercontent.com/10854265/109145173-0c2d7600-775a-11eb-815d-7baf35fcddc9.png">

**Comment by catiarodriguescosta** [comment]
https://github.com/wmcadigital/wmn-design-system/pull/667
This is fixed on the design system, which will be released next Thurs at 11 am. 
After that, I will need to update the design system version and in the next Umbraco release, it will be fixed.
Will close the issue once the design system version used in Umbraco is updated. 👍

**Comment by catiarodriguescosta** [comment]
> [wmcadigital/wmn-design-system#667](https://github.com/wmcadigital/wmn-design-system/pull/667)
> This is fixed on the design system, which will be released next Thurs at 11 am.
> After that, I will need to update the design system version and in the next Umbraco release, it will be fixed.
> Will close the issue once the design system version used in Umbraco is updated. 👍

https://beta.wmnetwork.co.uk/resources-and-support/resources-and-support-for-businesses/

**Comment by catiarodriguescosta** [comment]
Design system version updated. :)
