### ISSUE TITLE
Links in accordions are not rendering properly

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#52]
https://beta.wmnetwork.co.uk/plan-your-journey/travel-information/how-to-travel-with-accessibility-needs/get-help-if-you-have-a-disability-or-accessibility-need/ - RNIB Key fob

Link to "Get help" appears as ```https://beta.wmnetwork.co.uk/%7BlocalLink:umb://document/8d71f52a90ea45c2a66f67051e2af28b%7D```

But in the warning text further down the page, it renders as ```https://beta.wmnetwork.co.uk/get-help/contact-us/```

**Comment by catiarodriguescosta** [comment]
I've fixed that (there was a previous issue for that). But will reformulate the accordion so I'll make sure to test links before release.. :)
