### ISSUE TITLE
Create accounts for Jake/Kat/Tom

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#57]
Please create accounts in new Umbraco for:
- Jake
- Kat
- Tom

They need to be editors.

**Comment by daylesalmon** [comment]
@mrmjprice

All have been invited to beta.wmnetwork.co.uk as requested....
![image](https://user-images.githubusercontent.com/13015201/111463410-7319cb80-8717-11eb-8b2e-312a473bdf26.png)
