### ISSUE TITLE
Header link hover wrong colour

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#60]
<img width="314" alt="Screenshot 2021-03-23 at 10 43 04" src="https://user-images.githubusercontent.com/10854265/112134383-9aafde80-8bc4-11eb-8752-25a8e0de1d4e.png">

Hover for Translation & SEO Checker tabs do not match the content/media link:

<img width="186" alt="Screenshot 2021-03-23 at 10 44 02" src="https://user-images.githubusercontent.com/10854265/112134456-b0bd9f00-8bc4-11eb-87d8-dafc17ae7a7d.png">

**Comment by catiarodriguescosta** [comment]
Should be fixed on the dev environment. 👍
