### ISSUE TITLE
Stay up-to-date erroring on front end if the link is not overriden

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#62]
<img width="2073" alt="Screenshot 2021-03-23 at 10 50 48" src="https://user-images.githubusercontent.com/10854265/112135677-f29b1500-8bc5-11eb-934d-a9c81c782458.png">

Exploring RTE page

**Comment by mrmjprice** [comment]
This only happens when you first add the component.

If you override the link with a new link, it works.
If you override the link with a new link, then turn off the override, it works and goes to the default subscription link.
If you override the link with a new link, then remove the link and turn off the override, it works and goes to the default subscription link.

**Comment by catiarodriguescosta** [comment]
Same happening with Message (https://github.com/wmcadigital/wmn-cms/issues/81) and with the others components.

**Comment by catiarodriguescosta** [comment]
- [ ] Message
- [ ] Stay up to date
- [ ] Accordion
- [ ] Developer Card
- [ ] Navigation Card

**Comment by daylesalmon** [comment]
These are now all working and are on the dev environment. Will close as due to go live in next release.
