### ISSUE TITLE
Travel mode banner title

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#63]
The page title should appear as the H2 in the travel mode banner.

This should be marked up as the H1 with an override of H2.

**Comment by catiarodriguescosta** [comment]
<img width="706" alt="Screenshot 2021-03-25 at 11 59 24" src="https://user-images.githubusercontent.com/34938764/112470082-2448e300-8d62-11eb-88a2-c4145f7e4803.png">
<img width="490" alt="Screenshot 2021-03-25 at 11 59 38" src="https://user-images.githubusercontent.com/34938764/112470090-24e17980-8d62-11eb-9370-53bccca5b165.png">

Option to edit HTML was added.
Also I add the option to add macros to allow the future import reusable content feature.

**Comment by mrmjprice** [comment]
Hi Catia

Just to confirm that what you've got in ```<h1 class="h2">...</h1>``` should be ```<h1 class="h2">@Umbraco.Field("title")</h1>``` and not editable in this content editor.

The only thing this content editor should be putting in this text box is the description, like ```Walking is a great form of exercise...```

**Comment by mrmjprice** [comment]
(Not sure if @Umbraco.Field works anymore, but you understand what I mean? The page title is used here.)

**Comment by catiarodriguescosta** [comment]
<img width="1434" alt="Screenshot 2021-03-26 at 09 52 22" src="https://user-images.githubusercontent.com/34938764/112811327-dab70b80-9073-11eb-977d-09e3272a9e1b.png">

<img width="1435" alt="Screenshot 2021-03-26 at 09 52 41" src="https://user-images.githubusercontent.com/34938764/112811344-df7bbf80-9073-11eb-9b90-f69a71b4b602.png">
