### ISSUE TITLE
Remove ability to upload files from within content editor

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#64]
If we let people upload from within the content editor, the media files will become messy fairly quickly.

More importantly, content editors skip the requirement of marking their PDF as inaccessible.

Please can we remove upload from this?
<img width="805" alt="Screenshot 2021-03-23 at 11 22 57" src="https://user-images.githubusercontent.com/10854265/112139008-211aef00-8bca-11eb-8037-13a2ebafa1a1.png">

**Comment by catiarodriguescosta** [comment]
We did remove "upload" from all media pickers as discussed... 👍
