### ISSUE TITLE
Remove increase/decrease arrows from form (date of birth)

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#66]
<img width="267" alt="Screenshot 2021-03-23 at 11 39 50" src="https://user-images.githubusercontent.com/10854265/112140895-85d74900-8bcc-11eb-9991-1275e0821a05.png">

Should not have the arrows to the right-hand side of the field.

**Comment by catiarodriguescosta** [comment]
I think it is left by default. I didn't change that, just update the input with to make sure all the elements and arrows were okay.
Do you think it's relevant? Do you want me to change it?

**Comment by mrmjprice** [comment]
Could we remove the arrows altogether, please?
