### ISSUE TITLE
Content card - image tag still exists if no image

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#67]
```<img class="wmnds-content-card__image" src="" alt="">```
<img width="677" alt="Screenshot 2021-03-25 at 21 33 32" src="https://user-images.githubusercontent.com/10854265/112546755-c04e0b00-8db1-11eb-9027-d67d72cab421.png">

They should not have this tag, instead looking like:
<img width="683" alt="Screenshot 2021-03-25 at 21 34 17" src="https://user-images.githubusercontent.com/10854265/112546813-dcea4300-8db1-11eb-96dc-f7e98f9c25ce.png">

Example: https://beta.wmnetwork.co.uk/get-help/

**Comment by catiarodriguescosta** [comment]
I've fixed this, but it wasn't merged yet. So I did it again and you can test it on the dev environment: 
https://dev-wmnetwork.s1.umbraco.io/get-help/
