### ISSUE TITLE
Components not rendering using design system in back office

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#72]
<img width="379" alt="Screenshot 2021-03-26 at 08 19 32" src="https://user-images.githubusercontent.com/10854265/112602765-0041dc00-8e0c-11eb-89db-bc83abca0867.png">

<img width="815" alt="Screenshot 2021-03-26 at 08 19 40" src="https://user-images.githubusercontent.com/10854265/112602781-05069000-8e0c-11eb-8c1c-67ff21e8c5c3.png">

<img width="758" alt="Screenshot 2021-03-26 at 08 19 53" src="https://user-images.githubusercontent.com/10854265/112602807-0cc63480-8e0c-11eb-85d6-8bc1de8d7aca.png">

**Comment by daylesalmon** [comment]
This has been fixed and will go live in the next release.
