### ISSUE TITLE
Request: H2; H3; H4; H5; H6 in RTE also generate anchors/IDs

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#73]
This is so we can link to specific pieces of content across the website.

For example, the Get a refund page is very long with info for each scenario we refund.

**Comment by catiarodriguescosta** [comment]
Change is done and it is available on the staging website.
You can test it here: https://dev-wmnetwork.s1.umbraco.io/

**Comment by mrmjprice** [comment]
<img width="322" alt="Screenshot 2021-03-29 at 19 04 08" src="https://user-images.githubusercontent.com/10854265/112879822-92263f00-90c1-11eb-8156-551c4e9f3988.png">

**Comment by catiarodriguescosta** [comment]
I believe it will be fixed now. 
But let me know if there is any other case not working.
(it's hard to differentiate an h2 from RTE from any other h2 component and the method I'm using to do so could fail if somehow there is a class associated to the heading, but usually it's not..)

https://dev-wmnetwork.s1.umbraco.io/get-help/contact-us/
