### ISSUE TITLE
Accordion headings aren't vertically aligned to the center of the accordion

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#74]
## Describe the bug
The Accordion headings are not center vertically in the accordion box. Instead, the headings are currently placed more towards the top.

## Where is this happening?
On published pages

## Screenshots
![Screenshot 2021-03-26 at 09 08 41](https://user-images.githubusercontent.com/62507489/112608961-ddff8c80-8e12-11eb-9ec5-3921dc10aa16.png)

![Screenshot 2021-03-26 at 09 11 29](https://user-images.githubusercontent.com/62507489/112609279-4484aa80-8e13-11eb-89eb-714a28ce71cb.png)

**Comment by catiarodriguescosta** [comment]
Thanks!! It's fixed now and you can check it here: 
https://dev-wmnetwork.s1.umbraco.io/get-help/find-a-travel-centre/
