### ISSUE TITLE
Cannot move content within a row

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-cms#75]
I cannot drag and drop to reorder items in one row. E.g. I want to move form below accordions. However, I can move rows and sidebar items but not items within one row. 
<img width="732" alt="Screenshot 2021-03-26 at 09 37 41" src="https://user-images.githubusercontent.com/57525718/112613331-e1e1dd80-8e17-11eb-93b1-88dd3bf898db.png">

**Comment by mrmjprice** [comment]
@catiarodriguescosta - This might be due to the formatting not going across to the live Back Office.

**Comment by daylesalmon** [comment]
We've implemented a temp fix for this...It is an Umbraco bug and should hopefully be fixed in a new release. However our temp fix should resolve for our next release.
