### ISSUE TITLE
Travel by mode banner clear selection

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-cms#77]
When you click Travel mode dropdown and select for example bus but then decide that you don't want to select any modes and you want to clear that selection you need to click blank top row which is not immediately clear that it removes previously selected bus options. Can you add a text 'None'. So if user wants to clear their selection they click none and this doesn't show modal banner. 

<img width="882" alt="Screenshot 2021-03-26 at 09 52 16" src="https://user-images.githubusercontent.com/57525718/112615213-1c4c7a00-8e1a-11eb-97f6-1ba4c6caa78f.png">

**Comment by catiarodriguescosta** [comment]
I'm afraid I can't change the blank option to be "none". It's blank by default.
But what I can do is add any description to help editor to understand it... 

<img width="923" alt="Screenshot 2021-03-29 at 14 56 27" src="https://user-images.githubusercontent.com/34938764/112847444-fdaae500-909e-11eb-86cd-5b10f4c50513.png">

Any suggestions?

**Comment by mrmjprice** [comment]
Incorporated into #86
