### ISSUE TITLE
Remove 'Default value is false' label above toggles

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-cms#78]
## What's wrong?
Users don't need to know the default value of the toggles. When a content editor first edits a component or pattern, the default values will already be applied.

The cross and tickets of the toggles are self-explanatory so we don't need to add additional content on what value the toggle is set to.

**Comment by mrmjprice** [comment]
@daylesalmon May I suggest we have a call one day to rattle through all back office interface content changes?

**Comment by catiarodriguescosta** [comment]
@mrmjprice Do you want to schedule this?

**Comment by mrmjprice** [comment]
Scheduled for Thursday 😄

**Comment by mrmjprice** [comment]
Incorporated into #86
