### ISSUE TITLE
Implement eScooter brand

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#79]
Requires https://github.com/wmcadigital/wmn-design-system/issues/708 to be done first

**Comment by catiarodriguescosta** [comment]
- [ ] Pull request merged on design System
- [ ] Design system is released
- [ ] New version of the design system in Umbraco
- [ ] Update list of modes and update banner logic to have eScooter too
- [ ] Merge cc/feature/add-eScooter-mode into master
