### ISSUE TITLE
Message component is not being rendered

### ISSUE THREAD

**Issue by catiarodriguescosta** [wmcadigital/wmn-cms#81]
<img width="1068" alt="Screenshot 2021-03-29 at 13 22 53" src="https://user-images.githubusercontent.com/34938764/112835956-e0bbe500-9091-11eb-87eb-2a949cb9a19d.png">

Backoffice preview is working as expected!

**Comment by somtmee** [comment]
I noticed this too. You have to click on the component in the back office and click 'submit' in order for it to render on the front-end

**Comment by catiarodriguescosta** [comment]
Duplicate issue: https://github.com/wmcadigital/wmn-cms/issues/62.
Will close it.
