### ISSUE TITLE
Snippet Preview showing too many characters

### ISSUE THREAD

**Issue by somtmee** [wmcadigital/wmn-cms#82]
## Describe the bug
The snippet preview shows all of the description text, even if it's above the limit of 160. Google truncates descriptions at around 155-160 characters, so the snippet preview isn't giving content editors a true look at how the search result will appear on Google.

To give a true look, the search preview should cut off descriptions when they reach 160 and append '...' to the description as this is what Google does

## Where is this happening?
Search preview tab on a content page

## Screenshots
<img width="1107" alt="Screenshot 2021-03-31 at 09 47 35" src="https://user-images.githubusercontent.com/68843432/113117907-d53dfa80-9206-11eb-9f26-b496578c73a2.png">

**Comment by catiarodriguescosta** [comment]
@somtmee Maybe it's worth it to report this bug too if this is not there too: 
https://our.umbraco.com/packages/website-utilities/seo-checker/bugs/

**Comment by mrmjprice** [comment]
@somtmee can you report this to the SEO Checker folk? Closing this down as it's their bug.

**Comment by somtmee** [comment]
I've raised this with the plug-in author.
