### ISSUE TITLE
Character count unclear on search preview

### ISSUE THREAD

**Issue by somtmee** [wmcadigital/wmn-cms#83]
## Describe the bug
A bit pedantic, but it's not obvious that the numbers at the bottom of both the SEO title and SEO description inputs are character counts. Adding 'characters' after the number will help make this more obvious.

## Where is this happening?
Search preview of a content page

## Screenshots
<img width="1107" alt="Screenshot 2021-03-31 at 09 47 35" src="https://user-images.githubusercontent.com/68843432/113118246-2d74fc80-9207-11eb-98ff-3da713b30644.png">

**Comment by mrmjprice** [comment]
@somtmee Not sure how fixable this is because it's a package. Perhaps it's an idea to submit to the developer as an idea, same with the other suggestion for description?

It doesn't make sense to mess around with the package as there'll be a development cost every time the package has breaking changes.

**Comment by somtmee** [comment]
Cheers for letting me know it was a package. Yeah definitely don't want to mess with it. @catiarodriguescosta - can you point me in the direction of the package developer?

**Comment by catiarodriguescosta** [comment]
Hey Tom!! 
This is the guy: 
https://github.com/rsoeteman 
https://our.umbraco.com/members/id:2798/

What I suggest is to create a bug or feature request in the package page: https://our.umbraco.com/packages/website-utilities/seo-checker/ 
They have the links at the bottom of the page. :)

**Comment by mrmjprice** [comment]
@somtmee can you report this to the SEO Checker folk? Closing this down as it's their bug.
