### ISSUE TITLE
SEO validation doesn't pick up when focus keyword is in description

### ISSUE THREAD

**Issue by somtmee** [wmcadigital/wmn-cms#84]
## Describe the bug
The SEO validation check to see if the focus keyword is in the description seems to be returning the wrong result. In this case, it should have returned that the focus keyword WAS in the description

## Where is this happening?
Search preview on content page

## Screenshots
<img width="1125" alt="Screenshot 2021-03-31 at 10 01 54" src="https://user-images.githubusercontent.com/68843432/113119638-9446e580-9208-11eb-9f89-13f5e492f3be.png">

**Comment by catiarodriguescosta** [comment]
@somtmee same here:
https://our.umbraco.com/packages/website-utilities/seo-checker/bugs/

**Comment by mrmjprice** [comment]
@somtmee can you report this to the SEO Checker folk? Closing this down as it's their bug.

**Comment by somtmee** [comment]
I've raised this with the plug-in author.
