### ISSUE TITLE
Nested lists not formatting correctly in RTE

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#88]
They appear correctly on the live page, just not in the editor.

<img width="2481" alt="Screenshot 2021-04-14 at 09 05 38" src="https://user-images.githubusercontent.com/10854265/114675827-975dcd80-9d00-11eb-82da-4d757cbf36bb.png">

**Comment by mrmjprice** [comment]
https://beta.wmnetwork.co.uk/what-we-do/terms-and-conditions/swift-card/

**Comment by catiarodriguescosta** [comment]
Fixed! 👍
