### ISSUE TITLE
Form grid - not full-width

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#93]
<img width="707" alt="Screenshot 2021-05-04 at 15 02 27" src="https://user-images.githubusercontent.com/10854265/117015544-bf31c700-ace9-11eb-881f-730fae7bc879.png">

**Comment by catiarodriguescosta** [comment]
I've updated the title and description column class cause that one should be full width..
As we discussed, the fields on bigger screens are not full width.
(https://designsystem.wmnetwork.co.uk/patterns/question-form/)
