### ISSUE TITLE
Forms - strange vertical space

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#94]
Lots of gaps between fields which make it hard to use.

<img width="685" alt="Screenshot 2021-05-05 at 09 12 16" src="https://user-images.githubusercontent.com/10854265/117113166-0075b580-ad82-11eb-8b9f-fd067ee93fb4.png">

**Comment by catiarodriguescosta** [comment]
I did fix the space after the "title and description" field _ and it will be live tomorrow afternoon.
The space between the other fields seems right to me. :)

**Comment by catiarodriguescosta** [comment]
<img width="878" alt="Screenshot 2021-05-05 at 14 20 13" src="https://user-images.githubusercontent.com/34938764/117149094-c8d13280-adae-11eb-9b3c-4a02d01feb59.png">
