### ISSUE TITLE
Change breadcrumb logic to hide "Transport for West Midlands" instead of hiding "West Midlands Network"

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#98]
Remove Transport for West Midlands from breadcrumbs - Home > **Transport for West Midlands** > Swift and tickets > Manage your ticket > Get a refund or compensation

**Comment by daylesalmon** [comment]
It looked as though this had already been done. But I've updated the logic so it won't show anything in the root directory...so if a name change happens again, it will continue working.
